[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "google-play-scraper>=1.2.7",
    "pandas>=2.2.3",
    "streamlit>=1.42.2",
]
